[localhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2.7

[hardware]
server ansible_host=127.0.0.1 ansible_port=2222 ansible_user=root nsible_python_interpreter=/usr/bin/python2.7
